In [42]:
#Question 1
import numpy as np
a = np.arange(2,51,3)
print(a)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [43]:
#Question 2
a = [5,4,3,2,1]
b = [14,12,16,17,11]
a = np.array(a)
b = np.array(b)
con = np.concatenate((a,b))
print(con)
sort = np.sort(con)
print(sort)

[ 5  4  3  2  1 14 12 16 17 11]
[ 1  2  3  4  5 11 12 14 16 17]


In [44]:
#Question 3

arr = np.array([[1,2,3,3,2,1,4,5,6,7,1,2,8,2],[3,2,1,4,5,6,7,8]])
dimention = arr.shape
size = arr.size
print(dimention)
print(size)

(2,)
2


In [83]:
#Question 4
arr = np.array([1,2,3,4,5,6,7,8,9,10])
twod = np.expand_dims(arr,axis= 1)
print(twod)
#another way
td = arr[np.newaxis]
print(td)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[ 1  2  3  4  5  6  7  8  9 10]]


(1, 10)

In [86]:
#Question 5
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
hor = np.hstack((arr1,arr2))
ver = np.vstack((arr1,arr2))
print(hor)
print(ver)

[1 2 3 4 5 6 4 5 6 7 8 9]
[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


In [96]:
#Question 6
ar = np.array([1,2,2,1,4,5,6,78,4,5])
unique, count = np.unique(ar, return_counts= True)
b = np.asarray((unique, count))
print(b)

[[ 1  2  4  5  6 78]
 [ 2  2  2  2  1  1]]
